### ISSUE TITLE
Sending commands to camera...

### ISSUE THREAD

**Issue by shirandm** [simonjamain/CustomTimelapseCuraPlugin#4]
How this function works? Is this plug work with Ultimaker s5?
Thanks in advance

**Comment by simonjamain** [comment]
I don't know how this works, this is based on the M240 command, see : https://reprap.org/wiki/G-code#M240:_Trigger_camera

**Comment by simonjamain** [comment]
and I allowed to customize this command that will be sent while the printer isn't moving, just in case its needed
